# Generated by Django 4.1.1 on 2022-11-01 02:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hospital'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='passwordChangedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 10, 15, 46, 557285)),
        ),
        migrations.AlterField(
            model_name='items',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
