# Generated by Django 4.1.1 on 2022-11-01 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='passwordChangedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 16, 24, 12, 985501)),
        ),
    ]
