# Generated by Django 4.1.1 on 2022-11-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_passwordchangedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='passwordChangedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
