# Generated by Django 4.1.2 on 2022-11-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_passwordchangedat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'permissions': [('inventory_management', 'Manager can manage inventory'), ('inventory_list', 'Manager can view inventory'), ('manager_update_assets', 'Manager can update inventory information'), ('manager_delete_assets', 'Manager can delete inventory'), ('select_list', 'Manager can select inventory'), ('select', 'Manager can selct from global inventory')]},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'permissions': [('add_assets', 'Admin can add assets to the system'), ('update_assets', 'Admin can update asset details'), ('delete_assets', 'Admin can delete assets from system')]},
        ),
        migrations.AlterModelOptions(
            name='requests',
            options={'permissions': [('requested_list', 'Staff can view request list'), ('staff_request', 'Staff can request for inventory'), ('request_to', 'Manager can view requests by staff'), ('manager_update_request_to', 'Manager can update the request for inventory'), ('manager_delete_request_to', 'Manager can delete the request for inventory'), ('request_from_list', 'Manager can view the list of external requests'), ('manager_request_from', 'Manager can edit the external request'), ('approve', 'Manager can approve the external request')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
