# Generated by Django 4.1.2 on 2022-11-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_accountmanagement_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmanagement',
            options={'permissions': [('it_home', 'Admin can view IT home page'), ('manager_home', 'Manager can view Manager home page'), ('staff_home', 'Staff can view Staff home page'), ('account_management', 'Admin can view account details'), ('register_request', 'Admin can register accounts to system'), ('update_request', 'Admin can update account details'), ('update_password', 'Admin can update account password'), ('unlock_username', 'Admin can unlock a locked out account'), ('unlock_ip', 'Admin can unlock a locked out ip')]},
        ),
    ]
